server:
  port: 8081

spring:
  datasource-snippet:
    url: jdbc:mysql://localhost:3306/snippet
    username: iqbal
    password: iqbal
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
